#!/bin/bash

_run() {
  source $HOME/.bash/gitlab

  case $PWD in
    $HOME/devel/gitlab/*)
      if [[ "$(git config user.email)" = *"gitlab.com" ]]
      then
        exit 0
      else
        setup-git-gitlab

        echo "Success!"
        echo
        echo "Please, retry the last command"
        echo
        exit 1
      fi
      ;;
  esac
}

_run
