#!/bin/bash

source $HOME/.bash/git

setup-git-gitlab() {
  setup-git GitLab pleitzen@gitlab.com
}

alias srs="bin/spring rspec -f documentation --order rand"

srs-loop() {
  while :; do
    srs "$@" || break
  done
}

