#!/bin/bash

source $HOME/.bash/git

setup-git-gitlab() {
  setup-git GitLab pleitzen@gitlab.com
}

srs() {
  bin/spring rspec -f documentation --order "random:$RANDOM" "$@"
}

srs-loop() {
  while :; do
    srs "$@" || break
  done
}

